### ISSUE TITLE
Gives error when launching plugin in server saying main class not found.

### ISSUE THREAD

**Issue by xqwtxon** [xqwtxon/SlapperRotationV2#5]
# Information
Its Gives error when launching plugin in server saying main class not found.

# Explain
When you launch your server, its gives main class not found within version of 4.2.8+
since pocketmine will now require `src-namespace-prefix` on plugin.

# Code
```yml
name: ExamplePlugin
version: `.0.0
main: YourName\ExamplePlugin\Main
api: 4.2.8
src-namespace-prefix: YourName\ExamplePlugin
```

It would fixed by future or soon.
